# Generated by Django 3.1.2 on 2021-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210509_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbody',
            name='imdb',
            field=models.DecimalField(decimal_places=1, max_digits=20),
        ),
    ]
