# Generated by Django 3.1.2 on 2021-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210509_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbody',
            name='link_1080',
            field=models.CharField(blank=True, max_length=2000000, null=True),
        ),
    ]
