# Generated by Django 3.1.2 on 2021-05-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210509_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbody',
            name='language1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mainbody',
            name='language2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
